aggregation:
  base-url: http://localhost:8081/
  track-path: track
  shipment-path: shipments
  pricing-path: pricing
  cache:
    enabled: true
    port: 3000
    host: localhost
    expiration: 30m
