apiVersion: v1
kind: Service
metadata:
  name: aggregation-api-service
  labels:
    app: aggregation
spec:
  selector:
    app: aggregation-api
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004